/**
 * Mock reviews data matching MongoDB Review schema
 * Schema:
 * - _id (PK): Auto-generated by Mongoose/MongoDB
 * - productId (FK): Reference to Product collection
 * - userId (FK): Reference to User collection (nullable for guest reviews)
 * - content: String (required) - Review text content
 * - createdAt: Auto-generated timestamp
 */
export const MOCK_REVIEWS = [
  // Reviews for Product 1 - Premium Keychain Set
  {
    _id: '673a1b2c4d5e6f7a8b9c0d01',
    productId: '1',
    userId: 'user1',
    content: 'Absolutely love this keychain set! The quality is outstanding and the design is so elegant. The metal feels sturdy and the leather accents add a premium touch. Worth every penny!',
    createdAt: new Date('2024-10-15T08:30:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d02',
    productId: '1',
    userId: 'user2',
    content: 'Great product overall. The craftsmanship is impressive, though I wish there were more color options available. Still very happy with my purchase.',
    createdAt: new Date('2024-10-20T14:15:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d03',
    productId: '1',
    userId: null, // Guest review
    content: 'Perfect gift for my friend! She loved it. The packaging was also very nice.',
    createdAt: new Date('2024-11-01T10:45:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d04',
    productId: '1',
    userId: 'user1',
    content: 'This is my second purchase! The quality remains consistent. Great for gifts or personal use.',
    createdAt: new Date('2024-11-10T16:20:00Z').toISOString(),
  },

  // Reviews for Product 2 - Cute Plush Bear
  {
    _id: '673a1b2c4d5e6f7a8b9c0d05',
    productId: '2',
    userId: 'user2',
    content: 'This plush bear is incredibly soft and well-made! My daughter sleeps with it every night. The stitching is solid and it has held up perfectly after multiple washes.',
    createdAt: new Date('2024-09-25T09:00:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d06',
    productId: '2',
    userId: 'user1',
    content: 'Really cute and cuddly! Great quality for the price. I wish it came in a larger size option though.',
    createdAt: new Date('2024-10-05T13:30:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d07',
    productId: '2',
    userId: 'user2',
    content: 'Bought this as a gift and the recipient absolutely loved it! Super soft and adorable. Highly recommend!',
    createdAt: new Date('2024-11-10T11:45:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d08',
    productId: '2',
    userId: null,
    content: 'My kids love this bear! Worth the money for sure.',
    createdAt: new Date('2024-11-12T15:00:00Z').toISOString(),
  },

  // Reviews for Product 3 - Anime Figure
  {
    _id: '673a1b2c4d5e6f7a8b9c0d09',
    productId: '3',
    userId: 'admin1',
    content: 'Amazing detail on this figure! The paint job is flawless and the pose is dynamic. A must-have for any collector. Shipped carefully with excellent packaging.',
    createdAt: new Date('2024-10-12T17:20:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d0a',
    productId: '3',
    userId: 'user1',
    content: 'Great figure but slightly pricey. The quality justifies the cost though. Very happy with this addition to my collection.',
    createdAt: new Date('2024-10-28T12:10:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d0b',
    productId: '3',
    userId: 'user2',
    content: 'The details are incredible! Exactly as advertised. Packaging was secure and safe.',
    createdAt: new Date('2024-11-05T09:30:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d0c',
    productId: '3',
    userId: null,
    content: 'Great collectible item. Highly recommended for anime fans!',
    createdAt: new Date('2024-11-14T14:00:00Z').toISOString(),
  },

  // Reviews for Product 4 - Phone Accessories
  {
    _id: '673a1b2c4d5e6f7a8b9c0d0d',
    productId: '4',
    userId: 'user1',
    content: 'Exactly what I was looking for! The quality exceeded my expectations. Will definitely buy again.',
    createdAt: new Date('2024-11-05T10:15:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d0e',
    productId: '4',
    userId: 'user2',
    content: 'Good product, fast shipping. No complaints!',
    createdAt: new Date('2024-11-08T16:45:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d0f',
    productId: '4',
    userId: null,
    content: 'The case fits perfectly and looks great. Good protection for my phone.',
    createdAt: new Date('2024-11-13T11:20:00Z').toISOString(),
  },

  // Reviews for Product 5 - Lucky Cat Keychain
  {
    _id: '673a1b2c4d5e6f7a8b9c0d10',
    productId: '5',
    userId: 'user1',
    content: 'Love it! Exactly as described. The colors are vibrant and it looks great on my desk.',
    createdAt: new Date('2024-10-18T13:00:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d11',
    productId: '5',
    userId: 'user2',
    content: 'Such a cute lucky cat! Brings a smile to my face every day.',
    createdAt: new Date('2024-11-01T09:30:00Z').toISOString(),
  },

  // Reviews for Product 6 - Sparkle Accessories
  {
    _id: '673a1b2c4d5e6f7a8b9c0d12',
    productId: '6',
    userId: 'user2',
    content: 'Pretty good quality. Not perfect but definitely worth the price. Would recommend to friends.',
    createdAt: new Date('2024-10-22T15:30:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d13',
    productId: '6',
    userId: null,
    content: 'Nice product! Arrived on time and in perfect condition.',
    createdAt: new Date('2024-11-02T12:00:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d14',
    productId: '6',
    userId: 'user1',
    content: 'Beautiful accessories! The plating looks premium and elegant.',
    createdAt: new Date('2024-11-09T10:45:00Z').toISOString(),
  },

  // Reviews for Product 7 - Mini Plush Collection
  {
    _id: '673a1b2c4d5e6f7a8b9c0d15',
    productId: '7',
    userId: 'user2',
    content: 'Absolutely adorable! The details are incredible and it\'s so well made. My favorite purchase this year!',
    createdAt: new Date('2024-09-30T14:20:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d16',
    productId: '7',
    userId: 'user1',
    content: 'Collecting all of them! Each one is unique and super cute.',
    createdAt: new Date('2024-10-25T11:00:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d17',
    productId: '7',
    userId: null,
    content: 'Great quality for mini plushies. My kids love them!',
    createdAt: new Date('2024-11-07T16:30:00Z').toISOString(),
  },

  // Reviews for Product 8 - LED Light Keychain
  {
    _id: '673a1b2c4d5e6f7a8b9c0d18',
    productId: '8',
    userId: 'user1',
    content: 'Great value for money. Quality is solid and shipping was quick. Happy customer!',
    createdAt: new Date('2024-11-07T09:15:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d19',
    productId: '8',
    userId: 'user2',
    content: 'The LED light is bright and useful. Perfect for finding keys in the dark!',
    createdAt: new Date('2024-11-15T13:45:00Z').toISOString(),
  },

  // Reviews for Product 9 - Crystal Heart Keychain
  {
    _id: '673a1b2c4d5e6f7a8b9c0d1a',
    productId: '9',
    userId: 'user2',
    content: 'Beautiful craftsmanship! This exceeded all my expectations. The attention to detail is remarkable.',
    createdAt: new Date('2024-10-25T10:00:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d1b',
    productId: '9',
    userId: 'user1',
    content: 'Good product but took a while to arrive. Quality is nice though, so worth the wait.',
    createdAt: new Date('2024-11-09T14:30:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d1c',
    productId: '9',
    userId: null,
    content: 'The crystal sparkles beautifully! Makes a great gift.',
    createdAt: new Date('2024-11-16T11:15:00Z').toISOString(),
  },

  // Reviews for Product 10 - Vintage Leather Keychain
  {
    _id: '673a1b2c4d5e6f7a8b9c0d1d',
    productId: '10',
    userId: 'user1',
    content: 'Perfect! Exactly what I wanted. The quality is top-notch and it looks amazing!',
    createdAt: new Date('2024-11-03T15:00:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d1e',
    productId: '10',
    userId: 'user2',
    content: 'The genuine leather quality is excellent. Love the vintage brass finish!',
    createdAt: new Date('2024-11-11T12:30:00Z').toISOString(),
  },

  // Reviews for Product 11 - RGB Gaming Keychain
  {
    _id: '673a1b2c4d5e6f7a8b9c0d1f',
    productId: '11',
    userId: 'user1',
    content: 'Perfect for gamers! The RGB lighting is so cool. All my friends want one now.',
    createdAt: new Date('2024-10-20T09:45:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d20',
    productId: '11',
    userId: null,
    content: 'Cool design and the lights work perfectly. Great conversation starter!',
    createdAt: new Date('2024-11-08T14:00:00Z').toISOString(),
  },

  // Reviews for Product 12 - Floral Garden Keychain
  {
    _id: '673a1b2c4d5e6f7a8b9c0d21',
    productId: '12',
    userId: 'user2',
    content: 'The pressed flowers are so beautiful! Each one is unique and special.',
    createdAt: new Date('2024-10-15T11:20:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d22',
    productId: '12',
    userId: 'user1',
    content: 'Lovely botanical design. The resin preservation is done perfectly.',
    createdAt: new Date('2024-11-06T16:00:00Z').toISOString(),
  },

  // Reviews for Product 13 - Anime Character Keychain
  {
    _id: '673a1b2c4d5e6f7a8b9c0d23',
    productId: '13',
    userId: 'user1',
    content: 'Amazing quality acrylic prints! The characters look exactly like in the anime.',
    createdAt: new Date('2024-10-10T10:30:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d24',
    productId: '13',
    userId: 'user2',
    content: 'Collecting all my favorite characters! High quality printing and durable material.',
    createdAt: new Date('2024-10-28T13:15:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d25',
    productId: '13',
    userId: null,
    content: 'Perfect for anime fans! My son loves his Naruto keychain.',
    createdAt: new Date('2024-11-12T09:00:00Z').toISOString(),
  },

  // Reviews for Product 14 - Giant Teddy Bear
  {
    _id: '673a1b2c4d5e6f7a8b9c0d26',
    productId: '14',
    userId: 'user2',
    content: 'This giant bear is absolutely perfect! My daughter was so happy. Great quality and super soft!',
    createdAt: new Date('2024-10-05T14:45:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d27',
    productId: '14',
    userId: 'user1',
    content: 'Huge and cuddly! Made an excellent gift for my girlfriend. She absolutely loves it!',
    createdAt: new Date('2024-11-02T11:30:00Z').toISOString(),
  },

  // Reviews for Product 15 - Kawaii Cat Plushie
  {
    _id: '673a1b2c4d5e6f7a8b9c0d28',
    productId: '15',
    userId: 'user1',
    content: 'So kawaii! The Japanese design is authentic and the quality is amazing. Super soft!',
    createdAt: new Date('2024-09-28T10:15:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d29',
    productId: '15',
    userId: 'user2',
    content: 'Adorable cat plush! The expressions are so cute. I want to collect them all!',
    createdAt: new Date('2024-10-18T15:00:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d2a',
    productId: '15',
    userId: null,
    content: 'Perfect for cat lovers! Great quality and incredibly soft.',
    createdAt: new Date('2024-11-10T12:45:00Z').toISOString(),
  },

  // Reviews for Product 16 - Unicorn Rainbow Plush
  {
    _id: '673a1b2c4d5e6f7a8b9c0d2b',
    productId: '16',
    userId: 'user2',
    content: 'Magical unicorn! The rainbow mane is so colorful and sparkly. My daughter is obsessed!',
    createdAt: new Date('2024-10-08T09:30:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d2c',
    productId: '16',
    userId: 'user1',
    content: 'Beautiful plush! The wings are a great touch. High quality materials.',
    createdAt: new Date('2024-11-04T14:20:00Z').toISOString(),
  },

  // Reviews for Product 17 - Dinosaur Buddy Plush
  {
    _id: '673a1b2c4d5e6f7a8b9c0d2d',
    productId: '17',
    userId: 'user1',
    content: 'Perfect for dinosaur fans! My son loves his T-Rex. Great quality and very durable.',
    createdAt: new Date('2024-10-12T11:00:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d2e',
    productId: '17',
    userId: null,
    content: 'Cute dinosaurs! Educational and fun for kids. Bought all three species!',
    createdAt: new Date('2024-11-01T10:15:00Z').toISOString(),
  },

  // Reviews for Product 18 - Smart Watch Band
  {
    _id: '673a1b2c4d5e6f7a8b9c0d2f',
    productId: '18',
    userId: 'user1',
    content: 'Perfect fit for my Apple Watch! The silicone quality is excellent and comfortable.',
    createdAt: new Date('2024-10-22T13:30:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d30',
    productId: '18',
    userId: 'user2',
    content: 'Great selection of colors! I bought multiple bands to match different outfits.',
    createdAt: new Date('2024-11-09T15:45:00Z').toISOString(),
  },

  // Reviews for Product 19 - Wireless Earbuds Case
  {
    _id: '673a1b2c4d5e6f7a8b9c0d31',
    productId: '19',
    userId: 'user2',
    content: 'Protects my AirPods perfectly! The carabiner clip is very convenient.',
    createdAt: new Date('2024-10-30T11:20:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d32',
    productId: '19',
    userId: null,
    content: 'Good quality case. Fits snugly and looks nice.',
    createdAt: new Date('2024-11-13T09:30:00Z').toISOString(),
  },

  // Reviews for Product 20 - Laptop Sleeve
  {
    _id: '673a1b2c4d5e6f7a8b9c0d33',
    productId: '20',
    userId: 'user1',
    content: 'Excellent protection for my MacBook! The padding is thick and the water-resistant fabric is great.',
    createdAt: new Date('2024-10-16T14:00:00Z').toISOString(),
  },
  {
    _id: '673a1b2c4d5e6f7a8b9c0d34',
    productId: '20',
    userId: 'user2',
    content: 'Perfect size for my 15-inch laptop. Quality materials and construction.',
    createdAt: new Date('2024-11-05T16:15:00Z').toISOString(),
  },
];

// Export as mockReviews for backward compatibility
export const mockReviews = MOCK_REVIEWS;

/**
 * Helper function to get reviews by product ID
 * @param {string} productId - Product ID
 * @returns {Array} - Array of reviews for the product
 */
export const getReviewsByProductId = (productId) => {
  return MOCK_REVIEWS.filter(review => review.productId === productId);
};

/**
 * Helper function to get review by ID
 * @param {string} reviewId - Review ID
 * @returns {Object|null} - Review object or null
 */
export const getReviewById = (reviewId) => {
  return MOCK_REVIEWS.find(review => review._id === reviewId) || null;
};

/**
 * Helper function to get reviews by user ID
 * @param {string} userId - User ID
 * @returns {Array} - Array of reviews by the user
 */
export const getReviewsByUserId = (userId) => {
  return MOCK_REVIEWS.filter(review => review.userId === userId);
};

/**
 * Helper function to get review count for a product
 * @param {string} productId - Product ID
 * @returns {number} - Number of reviews
 */
export const getReviewCount = (productId) => {
  return getReviewsByProductId(productId).length;
};

/**
 * Helper function to get recent reviews across all products
 * @param {number} limit - Number of recent reviews to return
 * @returns {Array} - Array of recent reviews
 */
export const getRecentReviews = (limit = 10) => {
  return [...MOCK_REVIEWS]
    .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
    .slice(0, limit);
};

/**
 * Helper function to get paginated reviews for a product
 * @param {string} productId - Product ID
 * @param {number} skip - Number of reviews to skip
 * @param {number} limit - Number of reviews to return
 * @returns {Object} - Object with reviews array and pagination info
 */
export const getPaginatedReviews = (productId, skip = 0, limit = 10) => {
  const allReviews = getReviewsByProductId(productId);
  const sortedReviews = allReviews.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
  const paginatedReviews = sortedReviews.slice(skip, skip + limit);

  return {
    reviews: paginatedReviews,
    total: allReviews.length,
    hasMore: skip + limit < allReviews.length,
    skip,
    limit,
  };
};
