// Re-export common components for easier imports
export { default as LoadingSpinner } from './LoadingSpinner'
export { default as ErrorMessage } from './ErrorMessage'
export { default as PageHeader } from './PageHeader'
export { default as SearchBar } from './SearchBar'
export { default as AdvancedSearchBar } from './AdvancedSearchBar'
export { default as ScrollableContent } from './ScrollableContent'
export { default as ProductCard } from './ProductCard'
export { default as AuthFormLayout } from './AuthFormLayout'
export { default as Pagination } from './Pagination'
export { default as ProductBadges } from './ProductBadges'
export { default as VariantSelector } from './VariantSelector'
export { default as DiscountCodeInput } from './DiscountCodeInput'
export { default as AddressAutocomplete } from './AddressAutocomplete'

